language: c++

jobs:	
  include:
    - os: linux
      dist: trusty
      env: CC=mpicc CXX=mpic++

install:
    - if test "$CXX" == "mpic++" -a "$TRAVIS_OS_NAME" == "linux" ; then sudo apt-get install -y libopenmpi-dev openmpi-bin ; fi
    - source scripts/lammps.sh

script:
    - cd test/DCE/
    - mpirun -np 4 /home/travis/build/srmani/UCG-GFRD/lammps/src/lmp_mpi -in /home/travis/build/srmani/UCG-GFRD/test/DCE/cg_fm.inp