language: c++

jobs:	
  include:
    - os: linux
      dist: trusty
      env: CC=mpicc CXX=mpic++

install:
    - export PATH="$HOME/opt/bin:$PATH"
    - export CPATH="$HOME/opt/include:$CPATH"
    - export INCLUDE="$HOME/opt/include:$INCLUDE"
    - export LIBRARY_PATH="$HOME/opt/lib:$LIBRARY_PATH"
    - export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
    - if test "$CXX" == "mpic++" -a "$TRAVIS_OS_NAME" == "linux" ; then sudo apt-get install -y libopenmpi-dev openmpi-bin ; fi

script:
    - git clone -b stable https://github.com/lammps/lammps.git
    - cd lammps
    - cd src
    - make mpi